package org.greenbytes.http.sfv;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;
import java.util.function.Function;

/**
 * Represents the Parameters of an Item or an Inner List.
 * 
 * @see <a href=
 *      "https://www.rfc-editor.org/rfc/rfc8941.html#param">Section
 *      3.1.2 of RFC 8941</a>
 */
public class Parameters implements Map<String, Item<?>> {

    private final Map<String, Item<?>> delegate;

    public static final Parameters EMPTY = new Parameters(Collections.emptyMap());

    private Parameters(Map<String, Object> value) {
        this.delegate = Collections.unmodifiableMap(checkAndTransformMap(value));
    }

    /**
     * Creates a {@link Parameters} instance representing the specified
     * {@code Map<String, Item>} value.
     * <p>
     * Note that the {@link Map} implementation that is used here needs to
     * iterate predictably based on insertion order, such as
     * {@link java.util.LinkedHashMap}.
     * 
     * @param value
     *            a {@code Map<String, Item>} value
     * @return a {@link Parameters} representing {@code value}.
     */
    public static Parameters valueOf(Map<String, Object> value) {
        return new Parameters(value);
    }

    public StringBuilder serializeTo(StringBuilder sb) {
        for (Map.Entry<String, Item<?>> e : delegate.entrySet()) {
            sb.append(';').append(e.getKey());
            if (!(e.getValue().get().equals(Boolean.TRUE))) {
                sb.append('=');
                e.getValue().serializeTo(sb);
            }
        }
        return sb;
    }

    private static Map<String, Item<?>> checkAndTransformMap(Map<String, Object> map) {
        Map<String, Item<?>> result = new LinkedHashMap<>(
                Objects.requireNonNull(map, "Map must not be null").size());
        for (Map.Entry<String, Object> entry : map.entrySet()) {
            String key = Utils.checkKey(entry.getKey());
            Item<?> value = asItem(key, entry.getValue());
            if (!value.getParams().isEmpty()) {
                throw new IllegalArgumentException("Parameter value for '" + key + "' must be bare item (no parameters)");
            }
            result.put(entry.getKey(), value);
        }
        return result;
    }

    private static Item<?> asItem(String key, Object o) {
        if (o instanceof Item) {
            return (Item<?>) o;
        } else if (o instanceof Integer) {
            return IntegerItem.valueOf(((Integer) o).longValue());
        } else if (o instanceof Long) {
            return IntegerItem.valueOf((Long) o);
        } else if (o instanceof String) {
            return StringItem.valueOf((String) o);
        } else if (o instanceof Boolean) {
            return BooleanItem.valueOf((Boolean) o);
        } else if (o instanceof byte[]) {
            return ByteSequenceItem.valueOf((byte[]) o);
        } else if (o instanceof BigDecimal) {
            return DecimalItem.valueOf((BigDecimal)o);
        } else {
            throw new IllegalArgumentException("Can't map value for parameter '" + key + "': " + o.getClass());
        }
    }

    // delegate methods, autogenerated

    public void clear() {
        delegate.clear();
    }

    public Item<?> compute(String key,
                           BiFunction<? super String, ? super Item<?>, ? extends Item<?>> remappingFunction) {
        return delegate.compute(key, remappingFunction);
    }

    public Item<?> computeIfAbsent(String key,
                                   Function<? super String, ? extends Item<?>> mappingFunction) {
        return delegate.computeIfAbsent(key, mappingFunction);
    }

    public Item<?> computeIfPresent(String key,
                                    BiFunction<? super String, ? super Item<?>, ? extends Item<?>> remappingFunction) {
        return delegate.computeIfPresent(key, remappingFunction);
    }

    public boolean containsKey(Object key) {
        return delegate.containsKey(key);
    }

    public boolean containsValue(Object value) {
        return delegate.containsValue(value);
    }

    public Set<Entry<String, Item<?>>> entrySet() {
        return delegate.entrySet();
    }

    public boolean equals(Object o) {
        return delegate.equals(o);
    }

    public void forEach(BiConsumer<? super String, ? super Item<?>> action) {
        delegate.forEach(action);
    }

    public Item<?> get(Object key) {
        return delegate.get(key);
    }

    public Item<?> getOrDefault(Object key, Item<?> defaultValue) {
        return delegate.getOrDefault(key, defaultValue);
    }

    public int hashCode() {
        return delegate.hashCode();
    }

    public boolean isEmpty() {
        return delegate.isEmpty();
    }

    public Set<String> keySet() {
        return delegate.keySet();
    }

    public Item<?> merge(String key, Item<?> value,
            BiFunction<? super Item<?>, ? super Item<?>, ? extends Item<?>> remappingFunction) {
        return delegate.merge(key, value, remappingFunction);
    }

    public Item<?> put(String key, Item<?> value) {
        return delegate.put(key, value);
    }

    public void putAll(Map<? extends String, ? extends Item<?>> m) {
        delegate.putAll(m);
    }

    public Item<?> putIfAbsent(String key, Item<?> value) {
        return delegate.putIfAbsent(key, value);
    }

    public boolean remove(Object key, Object value) {
        return delegate.remove(key, value);
    }

    public Item<?> remove(Object key) {
        return delegate.remove(key);
    }

    public boolean replace(String key, Item<?> oldValue, Item<?> newValue) {
        return delegate.replace(key, oldValue, newValue);
    }

    public Item<?> replace(String key, Item<?> value) {
        return delegate.replace(key, value);
    }

    public void replaceAll(BiFunction<? super String, ? super Item<?>, ? extends Item<?>> function) {
        delegate.replaceAll(function);
    }

    public int size() {
        return delegate.size();
    }

    public Collection<Item<?>> values() {
        return delegate.values();
    }

    public String serialize() {
        return serializeTo(new StringBuilder()).toString();
    }
}
